CREATE TABLE TB_USER
(ID SERIAL PRIMARY KEY ,
NAME VARCHAR(200) NOT NULL ,
MAIL VARCHAR(200) NOT NULL ,
DATE_OF_BIRTH DATE NOT NULL,
JOB VARCHAR(150) NOT NULL,
PHONE CHAR(9) NOT NULL,
ADDRESS VARCHAR(200) NOT NULL,
REASON VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL);

CREATE TABLE TB_TASK
(ID SERIAL PRIMARY KEY,
NAME VARCHAR(150) NOT NULL,
DATE_CREATED DATE NOT NULL,
CATEGORY VARCHAR(100) NOT NULL,
STATUS BOOLEAN NOT NULL);

ALTER TABLE TB_TASK
ADD USER_ID INT NOT NULL;

ALTER TABLE TB_TASK
ADD CONSTRAINT FK_USER_TASK FOREIGN KEY(USER_ID) REFERENCES  TB_USER(ID);
